---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kopiur.home-operations.com/privileged-movers: "true"
    volsync.backube/privileged-movers: "true"
