---
apiVersion: authentik.starry.blue/v1alpha1
kind: AuthentikApplication
metadata:
  name: vikunja
spec:
  slug: vikunja
  name: Tasks
  adopt: IfMatch
  provider:
    flows:
      authorization:
        slug: default-provider-authorization-implicit-consent
      invalidation:
        slug: default-provider-invalidation-flow
    oauth2:
      clientType: Confidential
      redirectURIs:
        - url: "https://tasks.hoohoot.org/auth/openid/sso"
          matchingMode: Strict
          type: Authorization
      scopes:
        - scopeName: vikunja_scope
        - scopeName: openid
        - scopeName: email
        - scopeName: profile
      grantTypes:
        - AuthorizationCode
        - Hybrid
        - Implicit
        - ClientCredentials
        - Password
        - DeviceCode
        - RefreshToken
      subjectMode: HashedUserID
      issuerMode: PerProvider
      includeClaimsInIDToken: true
      credentials:
        secretRef:
          name: vikunja-oidc
  access:
    rules:
      - group:
          name: Hoohoot Users
      - group:
          name: SuperQuinQuin
