---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mattermost
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-sqq-secrets
  target:
    name: mattermost-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MM_SQLSETTINGS_DATASOURCE: "{{ .pg_uri }}"
        MM_SQLSETTINGS_DRIVERNAME: "postgres"
  dataFrom:
    - extract:
        key: postgres-sqq-pguser-mattermost
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-sqq-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
