---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: vaultwarden-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-id: "{{ .SSO_CLIENT_ID }}"
        client-secret: "{{ .SSO_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: default/vaultwarden/config
