---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: cross-seed-secret
    template:
      data:
        config.js: |
          module.exports = {
            torznab: [
              "http://prowlarr.downloads.svc.cluster.local/1/api?apikey={{ .PROWLARR__AUTH__APIKEY }}",
            ],
            torrentClients: [
               "qbittorrent:http://qbittorrent.downloads.svc.cluster.local:8080",
            ],
            delay: 30,
            action: "inject",
            matchMode: "safe",
            linkCategory: "cross-seed",
            linkDirs: ["/media/Downloads/qbittorrent/cross-seed"],
            dataDirs: ["/media/Downloads/qbittorrent/complete"],
            includeEpisodes: true,
            includeSingleEpisodes: true,
            includeNonVideos: true,
          };
  dataFrom:
    - extract:
        key: downloads/prowlarr
