---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homelab-manager
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    image:
      pullPolicy: IfNotPresent
    app:
      replicaCount: 1
      podAnnotations:
        reloader.stakater.com/auto: "true"
      podLabels:
        app: *app
      envFrom:
        - secretRef:
            name: homelab-manager-secret
      service:
        type: ClusterIP
        port: 80
      route:
        enabled: true
        parentRefs:
          - name: external
            namespace: network
        hostnames:
          - "${SECRET_DOMAIN}"
      resources:
        requests:
          cpu: 12m
          memory: 256Mi
        limits:
          memory: 1Gi
    operator:
      enabled: true
      replicaCount: 1
      envFrom:
        - secretRef:
            name: homelab-manager-secret
