---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homelab-manager
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      homelab-manager:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/lucas-dclrcq/homelab-manager
              tag: latest@sha256:8c7f8c235200feeb4f6095c25bccdfff4a5a919d7170f7994cb7c9032bd44697
            env:
              QUARKUS_HTTP_PORT: &port 80
            envFrom:
              - secretRef:
                  name: homelab-manager-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /q/health/live
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 10
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /q/health/ready
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 10
                  failureThreshold: 3
            resources:
              requests:
                cpu: 12m
                memory: 256Mi
              limits:
                memory: 1Gi
    service:
      main:
        controller: homelab-manager
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${LIMITED_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      tmp:
        type: emptyDir
        advancedMounts:
          homelab-manager:
            main:
              - path: /tmp
