---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homelab-manager-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: homelab-manager-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-id: "{{ .OIDC_CLIENT_ID }}"
        client-secret: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: default/homelab-manager/config
