---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: miniflux-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-id: "{{ .oidc_client_id }}"
        client-secret: "{{ .oidc_client_secret }}"
  dataFrom:
    - extract:
        key: default/miniflux
