---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rook-ceph-cluster
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.20.7
    digest: 5b93478620b4e197d4a88fb424ab2ec752ebe7a07df582d5fb0e5bd68e9242a5
  url: oci://ocharted.flux-system.svc.cluster.local:8080/charts.rook.io/release/rook-ceph-cluster
