---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: opencloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        IDM_ADMIN_PASSWORD: "{{ .INITIAL_ADMIN_PASSWORD }}"
        COLLABORA_ADMIN_USER: "{{ .COLLABORA_ADMIN_USER }}"
        COLLABORA_ADMIN_PASSWORD: "{{ .COLLABORA_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: default/opencloud
