---
apiVersion: authentik.starry.blue/v1alpha1
kind: AuthentikApplication
metadata:
  name: the-elder-scrobz
spec:
  slug: the-elder-scrobz
  name: The Elder Scrobz
  group: Media
  adopt: IfMatch
  provider:
    flows:
      authorization:
        slug: default-provider-authorization-implicit-consent
      invalidation:
        slug: default-provider-invalidation-flow
    oauth2:
      clientType: Confidential
      redirectURIs:
        - url: "http://localhost:3000/auth/authorized"
          matchingMode: Strict
          type: Authorization
        - url: "https://the-elder-scrobz.hoohoot.org/auth/authorized"
          matchingMode: Strict
          type: Authorization
      scopes:
        - scopeName: scrobz_role
        - scopeName: openid
        - scopeName: email
        - scopeName: profile
        - scopeName: offline_access
      grantTypes:
        - AuthorizationCode
        - Hybrid
        - Implicit
        - ClientCredentials
        - Password
        - DeviceCode
        - RefreshToken
      subjectMode: UserUsername
      issuerMode: PerProvider
      includeClaimsInIDToken: true
      credentials:
        secretRef:
          name: the-elder-scrobz-oidc
  access:
    rules:
      - group:
          name: Hoohoot Users
