---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: the-elder-scrobz-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: the-elder-scrobz-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-id: "{{ .SCROBZ_OIDC_CLIENT_ID }}"
        client-secret: "{{ .SCROBZ_OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: media/the-elder-scrobz
