---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sqq
components:
  - ../../components/common
resources:
  - ./database/ks.yaml
  - ./accueil/ks.yaml
  - ./sqq-inscription/ks.yaml
  - ./sqq-inscription-staging/ks.yaml
  - ./sqq-vente-groupee/ks.yaml
  - ./sqq-vente-groupee-staging/ks.yaml
  - ./sqq-sondages/ks.yaml
#  - ./sqq-choix-creneaux/ks.yaml
  - ./sqq-choix-creneaux-staging/ks.yaml
  - ./rocket-chat/ks.yaml
  - ./sqq-keycloak/ks.yaml
