{
 "title": "authentik",
 "description": "Grafana Dashboard for Prometheus metrics exposed by authentik.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Resources Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"auth\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"auth\", workload=~\"authentik-server|authentik-worker\", workload_type=\"deployment\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"auth\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"auth\", workload=~\"authentik-server|authentik-worker\", workload_type=~\"deployment\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Authentik Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "PolicyEngine Execution time by binding type",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(binding_target_name, binding_target_type) (rate(authentik_policies_execution_time_sum[5m]) / rate(authentik_policies_execution_time_count[5m]))"
    }
   ]
  },
  {
   "title": "PolicyEngine Execution time by binding target",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(object_name, object_type) (rate(authentik_policies_execution_time_sum[5m]) / rate(authentik_policies_execution_time_count[5m]))"
    }
   ]
  },
  {
   "title": "Task status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(authentik_system_tasks{status=\"TaskResultStatus.ERROR\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(authentik_system_tasks{status=\"TaskResultStatus.SUCCESSFUL\"})",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 20 },
   "options": {
    "content": "\n\n<img src=\"https://goauthentik.io/img/icon_top_brand.svg\">"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cached policies",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "authentik_policies_cached", "legendFormat": "Cached policies" },
    {
     "expr": "authentik_models{app=\"authentik_policies\", model_name=\"policy\"}",
     "legendFormat": "Total policies"
    }
   ]
  },
  {
   "title": "Connected Workers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(authentik_admin_workers)" }
   ]
  },
  {
   "title": "System task duration",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (task_name) (authentik_system_tasks)"
    }
   ]
  },
  {
   "title": "FlowPlanner time by flow",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (flow_slug) (rate(authentik_flows_plan_time_sum[5m]) / rate(authentik_flows_plan_time_count[5m]))"
    }
   ]
  }
 ]
}