---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agentgateway-crds
spec:
  interval: 1h
  releaseName: agentgateway-crds
  chartRef:
    kind: OCIRepository
    name: agentgateway-crds
