---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: seerr-db-secret
    template:
      engineVersion: v2
      data:
        DB_TYPE: "postgres"
        DB_HOST: '{{ index . "host" }}'
        DB_PORT: '{{ index . "port" }}'
        DB_NAME: '{{ index . "dbname" }}'
        DB_USER: '{{ index . "user" }}'
        DB_PASS: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: postgres-16-pguser-seerr
