---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app influxdb
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      influxdb:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: quay.io/influxdb/influxdb3-core
              tag: latest@sha256:70feb640721c04d84fba08a6d77cb953de3f441980ad44f9f398bb5b4c8f69de

            args:
              - --node-id=node0
              - --object-store=file
              - --data-dir=/var/lib/influxdb3

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true

            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 9999

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /var/lib/influxdb3
