---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onlyoffice
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: onlyoffice-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
  dataFrom:
    - extract:
        key: default/onlyoffice
