---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: keycloak-secret
    template:
      type: Opaque
      data:
        KC_DB_URL: '{{ index . "jdbc-uri" }}'
  dataFrom:
    - extract:
        key: postgres-16-pguser-keycloakx
