---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./allow-ingress-gateway-external.yaml
  - ./allow-ingress-gateway-internal.yaml
  - ./allow-egress-kubedns.yaml
  - ./allow-egress-postgres.yaml
