---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-mcp-server
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: vault-mcp-server-token
    template:
      engineVersion: v2
      data:
        VAULT_TOKEN: "{{ .VAULT_TOKEN }}"
  dataFrom:
    - extract:
        key: ai/vault-mcp-server
