apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:DHqiaynRqdYP3BKpVUZUCDF1nmYkVep+q01N7/0jPAkhi1xcrO9Ik+IVqz9vRckm6zWsN48tymDdgTOpOYbTPg==,iv:dTd3m+XzO3cegE09q8X1rvtMcV4RMKkiSQSXmpjkKms=,tag:LVTHNjUdnG2W7ee8RH5ziQ==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:tPskLBaBYtt2XAifBggRIsWxategnhgkov2+lA==,iv:DRcKrysyqecyKXghxq6mOIHHEez4pceSVMRGmdudoXI=,tag:3ErUEGo/0EV5BThdsx/LTQ==,type:str]
sops:
    age:
        - recipient: age18vvdvrkqql3pk74p72gawhlrk5ukltsz826cjt363kpdc8nnhs2suxews3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UlY0MHF2WEFFRzV6cTcy
            Tk8rNFpveE5HOVFTK3YyVmFYdDRSVGpsMWdzCitWUTh0dDZ0c1l4OUpiaG00OXh6
            Y2didU01YjVUNUNlbTVtbnZ0RklvNVkKLS0tIG5rakV0Z3hMdHc3dlduU0RZYTFl
            ZGxKc1RPdlB6ZTZuNjlzYWpEU1hxbkEKUP1VL8YdpsuMWIprVQ+6oTo4ARl0i4E4
            M34LJi9cs2v9k8HVVsbtJuC1Mbrw882WdU7gTOkE5M6X4tTZJiOhSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T21:06:49Z"
    mac: ENC[AES256_GCM,data:AZOE6AqfuOyZCq0wQ1S7u1Jl6ttf6fOWtFKZ2aP3wCh6zcnMqcqMaCQ43mQ7U0R+pORPvilDgKLyNmn0x3WnOpUrZBV91aD9HOJ6dSyQya154DzHBAij3eNLvPx4PaQtLW5PJIyzDIW1HOopsGfsI/qFusIEAQxD9CUOgsy3WkA=,iv:UnAY+7x3GuO7FBw4G4bkk7QiqwqYWHipYbPY5IQpNwM=,tag:Lu/rUovMGCN9HpFxXPHzIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
