---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: konflate-secret
    template:
      engineVersion: v2
      data:
        KONFLATE_WEBHOOK_SECRET: "{{ .KONFLATE_WEBHOOK_SECRET }}"
        KONFLATE_APP_CLIENT_ID: "{{ .GITHUB_APP_CLIENT_ID }}"
        KONFLATE_APP_PRIVATE_KEY: "{{ .GITHUB_APP_PRIVATE_KEY }}"
        KONFLATE_VERIFY_IMAGES: "true"
        KONFLATE_LOG_FORMAT: "json"
        KONFLATE_MCP: "true"
  dataFrom:
    - extract:
        key: flux-system/konflate/config
