{
 "title": "Home Sensors",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "room",
    "label": "Room",
    "query": "SELECT DISTINCT room FROM temperatures"
   }
  ]
 },
 "panels": [
  { "title": "Temperature & Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature / $room",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "repeat": "room",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Humidity / $room",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "repeat": "room",
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT observed_at, humidity \nFROM temperatures \nWHERE room = $room \nORDER BY observed_at DESC \nLIMIT 1 "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \n  observed_at as time,\n  temperature as value,\n  room as metric\nFROM temperatures\nWHERE $__timeFilter(observed_at) and ROOM = ANY(ARRAY[$room]::varchar[])\nORDER BY observed_at ASC"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT \n  observed_at as time,\n  humidity as value,\n  room as metric\nFROM temperatures\nWHERE $__timeFilter(observed_at) and ROOM = ANY(ARRAY[$room]::varchar[])\n    AND room != 'garden'\nORDER BY observed_at ASC"
    }
   ]
  },
  {
   "title": "Last 30 days Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket('24 hour', observed_at) AS period,\n    MIN(temperature) AS min,\n    AVG(temperature) as avg,\n    MAX(temperature) as max\nFROM temperatures\nWHERE room = ANY(ARRAY[$room]::varchar[])\n    AND room != 'garden'\nGROUP BY period;\n"
    }
   ]
  },
  {
   "title": "Last 30 days Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket('24 hour', observed_at) AS period,\n    MIN(humidity) AS min,\n    AVG(humidity) as avg,\n    MAX(humidity) as max\nFROM temperatures\nWHERE room = ANY(ARRAY[$room]::varchar[])\n    AND room != 'garden'\nGROUP BY period;\n"
    }
   ]
  },
  {
   "title": "Last Year Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket('1 week', observed_at) AS period,\n    MIN(temperature) AS min,\n    AVG(temperature) as avg,\n    MAX(temperature) as max\nFROM temperatures\nWHERE room = ANY(ARRAY[$room]::varchar[])\n    AND room != 'garden'\nGROUP BY period;\n"
    }
   ]
  },
  {
   "title": "Last Year Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket('1 week', observed_at) AS period,\n    MIN(humidity) AS min,\n    AVG(humidity) as avg,\n    MAX(humidity) as max\nFROM temperatures\nWHERE room = ANY(ARRAY[$room]::varchar[])\n    AND room != 'garden'\nGROUP BY period;\n"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Power Spikes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT \n  observed_at,\n  apparent_power\nFROM power "
    }
   ]
  },
  {
   "title": "Current Day Power Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COALESCE(\n            MAX(current_summ_delivered) - MIN(current_summ_delivered)\n        , 0) as today_total_delivered\nFROM power\nWHERE DATE(observed_at) = CURRENT_DATE;"
    }
   ]
  },
  {
   "title": "Current Day Power Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COALESCE(\n            MAX(current_summ_delivered) - MIN(current_summ_delivered)\n        , 0) / 1000 * 0.17686 as power_cost\nFROM power\nWHERE DATE(observed_at) = CURRENT_DATE;"
    }
   ]
  },
  {
   "title": "Daily Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "WITH days AS (\n    SELECT\n        generate_series(\n                        CURRENT_DATE - INTERVAL '6 days',\n                        CURRENT_DATE,\n                        '1 day'::interval\n        )::date as consumption_date\n),\n     daily_consumption AS (\n         SELECT\n             DATE(observed_at) as consumption_date,\n             COALESCE(\n                     MAX(current_summ_delivered) - MIN(current_summ_delivered)\n                 , 0) as daily_consumption\n         FROM power\n         WHERE DATE(observed_at) > CURRENT_DATE - INTERVAL '7 days'\n           AND DATE(observed_at) <= CURRENT_DATE\n         GROUP BY DATE(observed_at)\n     )\nSELECT\n    d.consumption_date as time,\n    COALESCE(dc.daily_consumption, 0) as daily_consumption\nFROM days d\n         LEFT JOIN daily_consumption dc USING (consumption_date)\nORDER BY d.consumption_date;"
    }
   ]
  },
  {
   "title": "Current Month Power Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COALESCE(\n            MAX(current_summ_delivered) - MIN(current_summ_delivered)\n        , 0) as today_total_delivered\nFROM power\nWHERE DATE(observed_at) >= DATE_TRUNC('month', CURRENT_DATE);"
    }
   ]
  },
  {
   "title": "Current Month Power Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COALESCE(\n            MAX(current_summ_delivered) - MIN(current_summ_delivered)\n        , 0) / 1000 * 0.17686 as power_cost\nFROM power\nWHERE DATE(observed_at) >= DATE_TRUNC('month', CURRENT_DATE);"
    }
   ]
  },
  {
   "title": "Monthly Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "WITH months AS (\n    SELECT\n        generate_series(\n            date_trunc('month', CURRENT_DATE) - INTERVAL '11 months',\n            date_trunc('month', CURRENT_DATE),\n            '1 month'::interval\n        )::date as consumption_month\n),\n     monthly_consumption AS (\n         SELECT\n             date_trunc('month', observed_at)::date as consumption_month,\n             COALESCE(\n                 MAX(current_summ_delivered) - MIN(current_summ_delivered)\n             , 0) as monthly_consumption\n         FROM power\n         WHERE observed_at > date_trunc('month', CURRENT_DATE) - INTERVAL '12 months'\n           AND observed_at <= CURRENT_DATE\n         GROUP BY date_trunc('month', observed_at)::date\n     )\nSELECT\n    m.consumption_month as time,\n    COALESCE(mc.monthly_consumption, 0) as monthly_consumption\nFROM months m\n     LEFT JOIN monthly_consumption mc USING (consumption_month)\nORDER BY m.consumption_month;"
    }
   ]
  }
 ]
}