---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oxicloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: oxicloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # DB
        OXICLOUD_DB_CONNECTION_STRING: "{{ .pg_uri }}"
        DATABASE_URL: "{{ .pg_uri }}"
        # OIDC
        OXICLOUD_OIDC_ENABLED: "true"
        OXICLOUD_OIDC_DISABLE_PASSWORD_LOGIN: "true"
        OXICLOUD_OIDC_ADMIN_GROUPS: "{{ .OIDC_ADMIN_GROUPS }}"
        OXICLOUD_OIDC_PROVIDER_NAME: "SSO"
        OXICLOUD_OIDC_ISSUER_URL: "https://sso.${SECRET_DOMAIN}/application/o/oxicloud/"
        OXICLOUD_OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OXICLOUD_OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OXICLOUD_OIDC_REDIRECT_URI: "https://drive.${SECRET_DOMAIN}/api/auth/oidc/callback"
        OXICLOUD_OIDC_FRONTEND_URL: "https://drive.${SECRET_DOMAIN}"
        OXICLOUD_OIDC_SCOPES: "openid profile email"
        OXICLOUD_OIDC_AUTO_PROVISION: "true"
  dataFrom:
    - extract:
        key: default/oxicloud
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-oxicloud
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
