---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oxicloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: oxicloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OXICLOUD_DB_CONNECTION_STRING: "{{ .pg_uri }}"
        DATABASE_URL: "{{ .pg_uri }}"
  dataFrom:
    - extract:
        key: postgres-16-pguser-oxicloud
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
