---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: nana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NANA_DB_URL: "{{ .pg_uri }}"
        NANA_ANNAS_ARCHIVE_SECRET_KEY: "{{ .NANA_ANNAS_ARCHIVE_SECRET_KEY }}"
        NANA_AUTH_HEADER_NAME: "X-Authentik-Username"
        NANA_ANNAS_ARCHIVE_MIRROR_URL: "https://annas-archive.gl"
        NANA_WEBHOOK_ENABLED: "true"
        NANA_WEBHOOK_URL: "http://homelab-manager.default.svc.cluster.local/api/notifications/nana"
  dataFrom:
    - extract:
        key: media/nana
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-nana
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
