---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookboss
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: bookboss-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BOOKBOSS__OIDC__DISCOVERY_URL: "https://sso.${SECRET_DOMAIN}/application/o/bookboss/"
        BOOKBOSS__OIDC__CLIENT_ID: "{{ .BOOKBOSS__OIDC__CLIENT_ID }}"
        BOOKBOSS__OIDC__CLIENT_SECRET: "{{ .BOOKBOSS__OIDC__CLIENT_SECRET }}"
        BOOKBOSS__OIDC__BUTTON_LABEL: "SSO"
        BOOKBOSS__OIDC__AUTO_PROVISION: "true"
        BOOKBOSS__DATABASE__DATABASE_URL: "{{ .pg_uri }}"
        BOOKBOSS__ENCRYPTION_SECRET: "{{ .BOOKBOSS_ENCRYPTION_SECRET }}"
        BOOKBOSS__ANNAS_ARCHIVE__ENABLED: "true"
        BOOKBOSS__ANNAS_ARCHIVE__MIRROR_URL: "https://annas-archive.gd"
        BOOKBOSS__ANNAS_ARCHIVE__API_KEY: "{{ .BOOKBOSS__ANNAS_ARCHIVE__API_KEY }}"
  dataFrom:
    - extract:
        key: media/bookboss
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-bookboss
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
