---
apiVersion: authentik.starry.blue/v1alpha1
kind: AuthentikApplication
metadata:
  name: komga
spec:
  slug: komga
  name: Komga
  group: Media
  adopt: IfMatch
  provider:
    flows:
      authorization:
        slug: default-provider-authorization-implicit-consent
      invalidation:
        slug: default-provider-invalidation-flow
    oauth2:
      clientType: Confidential
      redirectURIs:
        - url: "https://komga.hoohoot.org/login/oauth2/code/keycloak"
          matchingMode: Strict
          type: Authorization
      scopes:
        - scopeName: openid
        - scopeName: email
        - scopeName: profile
      grantTypes:
        - AuthorizationCode
        - Hybrid
        - Implicit
        - ClientCredentials
        - Password
        - DeviceCode
        - RefreshToken
      subjectMode: UserUsername
      issuerMode: PerProvider
      includeClaimsInIDToken: true
      credentials:
        secretRef:
          name: komga-oidc
  access:
    rules:
      - group:
          name: Hoohoot Users
