---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: grafana-mcp-token
    template:
      engineVersion: v2
      data:
        token: "{{ .token }}"
  dataFrom:
    - extract:
        key: ai/grafana-mcp
