---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recherche-maison
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: recherche-maison-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DEEPSEEK_API_KEY: "{{ .DEEPSEEK_API_KEY }}"
        MAISON_DB_URL: 'jdbc:postgresql://{{ .pg_host }}:{{ .pg_port }}/{{ .pg_dbname }}'
        MAISON_DB_USER: '{{ .pg_user }}'
        MAISON_DB_PASSWORD: '{{ .pg_password }}'
  dataFrom:
    - extract:
        key: default/recherche-maison
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-recherchemaison
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
