---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: renovate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RENOVATE_TOKEN: '{{ .github_token | default "" }}'
        GITHUB_COM_TOKEN: '{{ .github_token | default "" }}'
        OCHARTED_PASSWORD: '{{ .ocharted_password | default "" }}'
  dataFrom:
    - extract:
        key: development/renovate
    - extract:
        key: flux-system/ocharted/config
      rewrite:
        - regexp:
            source: "^password$"
            target: "ocharted_password"
