---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app renovate-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    route:
      enabled: true
      hostnames:
        - "renovate.${LIMITED_DOMAIN}"
      parentRefs:
        - name: internal
          namespace: network
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      dashboard:
        enabled: true
        grafanaDashboard:
          allowCrossNamespaceImport: true
          instanceSelector:
            matchLabels:
              grafana.internal/instance: grafana
