---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: forgejo-secret
    template:
      engineVersion: v2
      data:
        FORGEJO__database__DB_TYPE: postgres
        FORGEJO__database__HOST: "{{ .pg_host }}:{{ .pg_port }}"
        FORGEJO__database__NAME: "{{ .pg_dbname }}"
        FORGEJO__database__USER: "{{ .pg_user }}"
        FORGEJO__database__PASSWD: "{{ .pg_password }}"
        FORGEJO__database__SSL_MODE: disable
  dataFrom:
    - extract:
        key: postgres-16-pguser-forgejo
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
