---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app forgejo
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      forgejo:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: codeberg.org/forgejo/forgejo
              tag: 11.0.4

            envFrom:
              - secretRef:
                  name: forgejo-secret

            env:
              FORGEJO__server__DOMAIN: "git.${SECRET_DOMAIN}"
              FORGEJO__server__ROOT_URL: "https://git.${SECRET_DOMAIN}"
              FORGEJO__server__HTTP_PORT: &http_port 3000
              FORGEJO__server__SSH_DOMAIN: "git.${SECRET_DOMAIN}"
              FORGEJO__server__SSH_PORT: 22
              FORGEJO__server__SSH_LISTEN_PORT: &ssh_port 22
              FORGEJO__server__START_SSH_SERVER: "true"
              FORGEJO__server__LANDING_PAGE: login
              FORGEJO__service__DISABLE_REGISTRATION: "false"
              FORGEJO__service__REQUIRE_SIGNIN_VIEW: "true"
              FORGEJO__service__ENABLE_NOTIFY_MAIL: "true"
              FORGEJO__mailer__ENABLED: "true"
              FORGEJO__mailer__PROTOCOL: smtp
              FORGEJO__mailer__SMTP_ADDR: smtp-relay.infrastructure.svc.cluster.local
              FORGEJO__mailer__SMTP_PORT: "2525"
              FORGEJO__mailer__FROM: "git@${SECRET_DOMAIN}"
              FORGEJO__metrics__ENABLED: "true"
              FORGEJO__log__LEVEL: warn
              FORGEJO__security__INSTALL_LOCK: "true"
              USER_UID: "${APP_UID}"
              USER_GID: "${APP_GID}"
              TZ: "${TIMEZONE}"

            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/healthz
                    port: *http_port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/healthz
                    port: *http_port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 5

            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 2Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *http_port
      ssh:
        controller: *app
        type: LoadBalancer
        loadBalancerIP: "${LB_IP_FORGEJO_SSH}"
        externalTrafficPolicy: Local
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "git.${LIMITED_DOMAIN}"
        ports:
          ssh:
            port: *ssh_port
            targetPort: *ssh_port
            protocol: TCP

    serviceMonitor:
      app:
        serviceName: forgejo
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            group: Misc
        hostnames:
          - "git.${SECRET_DOMAIN}"
        parentRefs:
          - name: external
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *http_port

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
