---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sqq-choix-creneaux-staging
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: sqq-choix-creneaux-staging-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        QUARKUS_DATASOURCE_JDBC_URL: '{{ index . "jdbc-uri" }}'
        QUARKUS_OIDC_CREDENTIALS_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        BREVO_API_KEY: "{{ .BREVO_API_KEY }}"
        BREVO_CONFIRMATION_TEMPLATE_ID: "{{ .BREVO_CONFIRMATION_TEMPLATE_ID }}"
        BREVO_REMINDER_TEMPLATE_ID: "{{ .BREVO_REMINDER_TEMPLATE_ID }}"
        ODOO_URL: "{{ .ODOO_URL }}"
        ODOO_DB: "{{ .ODOO_DB }}"
        ODOO_USERNAME: "{{ .ODOO_USERNAME }}"
        ODOO_PASSWORD: "{{ .ODOO_PASSWORD }}"
  dataFrom:
    - extract:
        key: sqq/sqq-choix-creneaux-staging
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-sqqchoixcreneauxstaging
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
