---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sqq-choix-creneaux-staging
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      main:
        replicas: 1
        containers:
          main:
            image:
              repository: ghcr.io/superquinquin-sur-deule/sqq-choix-creneaux
              tag: latest

            env:
              QUARKUS_OIDC_AUTH_SERVER_URL: "https://auth.${SQQ_DOMAIN}/realms/sqq-staging"
              QUARKUS_OIDC_CLIENT_ID: choix-creneaux-staging
              APP_URL: "https://choix-creneaux-staging.${SQQ_DOMAIN}"

            envFrom:
              - secretRef:
                  name: sqq-choix-creneaux-staging-secret

            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /q/health/live
                    port: 8080
                  periodSeconds: 10
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /q/health/ready
                    port: 8080
                  periodSeconds: 10
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /q/health/started
                    port: 8080
                  periodSeconds: 5
                  failureThreshold: 60

            resources:
              requests:
                cpu: 50m
                memory: 256M
              limits:
                memory: 1Gi

    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8080

    route:
      app:
        hostnames:
          - "choix-creneaux-staging.${SQQ_DOMAIN}"
        parentRefs:
          - name: external
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
