apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repository-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:SP18e+eKwav+J6wlT8yp91kTvr3eGFZe4r3YgagyjQ6ppoiaXQEtveOtN6MOno14Rw49hScyawvSz3QrVqnL7g==,iv:fUvatqiw64BxVK/iLaZLCAXBr7mN/t+0hUHSMDZBp+8=,tag:NnO5b1z9lljUp6DNuKHjHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUm13RlNPanlCclVOMnYy
            eHppYjRXaHVWLy95TlNnMm0zNmJscytaYVVnClpSZkRUVVNyQVpoaTYvK3YwMFNz
            OEczM1gwYnoyVGVQUjZGb0JXYjh4MXcKLS0tIFQvS0trWmcrVWZQQ3VXZDgrUks3
            WHpFNE0xWkRSSDl4K0UzOUtOMlNUY3MKt+ujIPMax8SoYwGzLotvY2CKQKV6ZckT
            seA0LgYCAj83vsm+P+coRA9dY74ND+M6YMibWFv8IHcO3cgsDavqDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18vvdvrkqql3pk74p72gawhlrk5ukltsz826cjt363kpdc8nnhs2suxews3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T14:58:29Z"
    mac: ENC[AES256_GCM,data:hgv6cueJPpXpHaT4Jh05SXdLrxcDVi8cbCsIn4LLOS6PDhCoiWq6amZwZAf02fZc9mzZZqfW/Kd+jDwiWbMLZaU7h4/j9ppxCd/F65qeDnRO5/D6EVpn7u0RYud41Pd+P6ojnaofObzcf/lACGoGwbjJTWuZN8sSuIscu1X8bDs=,iv:GgLwkvQzlltKKc845q/Qc2z1ev1Vps6mkX+nPoPkjyA=,tag:vSJyvHvjQ2LO5j7037WRlQ==,type:str]
    version: 3.13.3
