---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: forgejo-secret
    template:
      engineVersion: v2
      data:
        password: "{{ .pg_password }}"
        key: "{{ .OIDC_CLIENT_ID }}"
        secret: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: default/forgejo
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-forgejo
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
