---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app forgejo
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    image:
      rootless: true
      registry: code.forgejo.org
      repository: forgejo/forgejo
      tag: 16.0.1

    persistence:
      create: false
      claimName: *app

    service:
      ssh:
        type: LoadBalancer
        port: &sshPort 22
        loadBalancerIP: "${LB_IP_FORGEJO_SSH}"
        externalTrafficPolicy: Local
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "git.${LIMITED_DOMAIN}"

    httpRoute:
      enabled: false

    tcpRoute:
      enabled: false

    gitea:
      admin:
        username: ""
      additionalConfigFromEnvs:
        - name: FORGEJO__database__PASSWD
          valueFrom:
            secretKeyRef:
              name: forgejo-secret
              key: password
      config:
        database:
          DB_TYPE: postgres
          HOST: postgres-16-primary.infrastructure.svc.cluster.local:5432
          NAME: forgejo
          USER: forgejo
          SSL_MODE: disable
        cache:
          ENABLED: true
          ADAPTER: redis
          HOST: redis://forgejo-dragonfly:6379?pool_size=100&idle_timeout=180s
        queue:
          TYPE: redis
          CONN_STR: redis://forgejo-dragonfly:6379?pool_size=100&idle_timeout=180s
        session:
          PROVIDER: redis
          PROVIDER_CONFIG: redis://forgejo-dragonfly:6379?pool_size=100&idle_timeout=180s
          SESSION_LIFE_TIME: "1209600"
        server:
          DOMAIN: "git.${SECRET_DOMAIN}"
          ROOT_URL: "https://git.${SECRET_DOMAIN}"
          SSH_DOMAIN: "git.${SECRET_DOMAIN}"
          SSH_PORT: *sshPort
          APP_DATA_PATH: /data/gitea
          LANDING_PAGE: login
        repository:
          DEFAULT_REPO_UNITS: repo.code,repo.releases,repo.issues,repo.pulls,repo.actions
          DISABLED_REPO_UNITS: repo.ext_wiki,repo.ext_issues
          ROOT: /data/git/repositories
        repository.pull-request:
          DEFAULT_MERGE_STYLE: squash
        lfs:
          PATH: /data/git/lfs
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
        mailer:
          ENABLED: true
          PROTOCOL: smtp
          SMTP_ADDR: smtp-relay.infrastructure.svc.cluster.local
          SMTP_PORT: "2525"
          FROM: "git@${SECRET_DOMAIN}"
        metrics:
          ENABLED: true
        log:
          LEVEL: warn
        openid:
          ENABLE_OPENID_SIGNIN: false
          ENABLE_OPENID_SIGNUP: false
        service:
          DISABLE_REGISTRATION: true
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true
          ENABLE_INTERNAL_SIGNIN: false
          ENABLE_PASSWORD_SIGNIN_FORM: false
          SHOW_REGISTRATION_BUTTON: false
          ENABLE_NOTIFY_MAIL: true
        service.explore:
          REQUIRE_SIGNIN_VIEW: true
        oauth2_client:
          ENABLE_AUTO_REGISTRATION: true
          USERNAME: preferred_username
          UPDATE_AVATAR: true
          ACCOUNT_LINKING: auto
        security:
          INSTALL_LOCK: true
      oauth:
        - name: Authentik
          provider: openidConnect
          existingSecret: forgejo-secret
          autoDiscoverUrl: "https://sso.${SECRET_DOMAIN}/application/o/forgejo/.well-known/openid-configuration"
          scopes: "openid profile email"
