---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: tracearr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
        COOKIE_SECRET: "{{ .COOKIE_SECRET }}"
        DATABASE_URL: "postgres://tracearr:{{ .DB_PASSWORD }}@tracearr-timescaledb.media.svc.cluster.local:5432/tracearr"
        REDIS_URL: "redis://tracearr-dragonfly.media.svc.cluster.local:6379/0"
  dataFrom:
    - extract:
        key: media/tracearr
