---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: tracearr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .tracearr_jwt_secret }}"
        COOKIE_SECRET: "{{ .tracearr_cookie_secret }}"
        DATABASE_URL: "{{ .pg_uri }}"
  dataFrom:
    - extract:
        key: media/tracearr
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
      rewrite:
        - regexp:
            source: "(.*)"
            target: "tracearr_$1"
    - extract:
        key: postgres-16-pguser-tracearr
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
