---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tracearr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/connorgallopo/tracearr
              tag: 1.4.28
            env:
              NODE_ENV: production
              TZ: Europe/Paris
              CORS_ORIGIN: "https://{{ .Release.Name }}.${LIMITED_DOMAIN}"
              PORT: &port 3000
              TRUST_PROXY: "true"
              REDIS_URL: "redis://{{ .Release.Name }}-dragonfly:6379"
              LOG_LEVEL: info
            envFrom:
              - secretRef:
                  name: tracearr-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: [ALL]}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    route:
      main:
        hostnames:
          - "{{ .Release.Name }}.${LIMITED_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network

    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/data
      tmpfs:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /tmp
                subPath: tmp
