---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: tracearr
spec:
  interval: 1m
  module: http_2xx
  prober:
    url: blackbox-exporter-lan.observability.svc.cluster.local.:9115
  targets:
    staticConfig:
      static:
        - "https://tracearr.${LIMITED_DOMAIN}"
  metricRelabelings:
    - targetLabel: service
      replacement: app-endpoint
      action: replace
