---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: harbor-secret
    template:
      engineVersion: v2
      data:
        HARBOR_ADMIN_PASSWORD: "{{ .HARBOR_ADMIN_PASSWORD }}"
        secretKey: "{{ .HARBOR_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: development/harbor
