---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: harbor-secret
    template:
      engineVersion: v2
      data:
        HARBOR_ADMIN_PASSWORD: "{{ .HARBOR_ADMIN_PASSWORD }}"
        secretKey: "{{ .HARBOR_SECRET_KEY }}"
        CONFIG_OVERWRITE_JSON: |
          {
            "auth_mode": "oidc_auth",
            "oidc_name": "SSO",
            "oidc_endpoint": "https://sso.${SECRET_DOMAIN}/application/o/harbor/",
            "oidc_client_id": "{{ .OIDC_CLIENT_ID }}",
            "oidc_client_secret": "{{ .OIDC_CLIENT_SECRET }}",
            "oidc_groups_claim": "groups",
            "oidc_admin_group": "{{ .OIDC_ADMIN_GROUP }}",
            "oidc_scope": "openid,profile,email,offline_access",
            "oidc_verify_cert": true,
            "oidc_auto_onboard": true,
            "oidc_user_claim": "preferred_username"
          }
  dataFrom:
    - extract:
        key: development/harbor
