---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kazib
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      app:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/oknozor/kazib
              tag: latest@sha256:d6f149c786e25d174a3f680f003428848a8df04be58e11b3dfeccd0febc696d7
            env:
              PORT: &port 8080
              IP: 0.0.0.0
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: ${APP_UID}
        runAsGroup: ${APP_GID}
        fsGroup: ${APP_GID}
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: external
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      db:
        existingClaim: *app
        globalMounts:
          - path: /app/data
      books:
        type: nfs
        server: "truenas.${INTERNAL_DOMAIN}"
        path: /mnt/tank/Media/Books
