---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app federation-tester
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      federation-tester:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/mtrnord/rust-federation-tester
              tag: 0.4.0

    service:
      app:
        controller: federation-tester
        ports:
          http:
            port: 8080

    persistence:
      config:
        type: configMap
        name: federation-tester-config
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
      data:
        type: emptyDir
        globalMounts:
          - path: /data
