---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: federation-tester
spec:
  groups:
    - name: federation-tester.rules
      rules:
        - alert: FederationTesterFailure
          expr: |
            federation_request_total{server="${SECRET_DOMAIN}", outcome="failure"} > 0
          for: 5m
          annotations:
            summary: >-
              Federation test failure detected for {{ $labels.server }}
          labels:
            severity: critical
