---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crunchy-pgo-sqq
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: crunchy-pgo-sqq-secret
    template:
      engineVersion: v2
      type: Opaque
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .s3_key }}
          repo1-s3-key-secret={{ .s3_key_secret }}
  dataFrom:
    - extract:
        key: sqq/database/pgbackrest
      rewrite:
        - regexp:
            source: "-"
            target: "_"
