---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name postgres-sqq
  labels:
    crunchy-users.henrywhitaker3.github.com/watch: "true"
  annotations:
    crunchy-users.henrywhitaker3.github.com/superuser: "postgres"
spec:
  postgresVersion: 17

  service:
    type: LoadBalancer
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "sqq.postgres.${LIMITED_DOMAIN}"
        io.cilium/lb-ipam-ips: "${LB_IP_PG_SQQ}"

  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        parameters:
          max_connections: 300
        max_wal_size: 5GB
        synchronous_commit: "on"
        pg_hba:
          - hostnossl all all 10.69.0.0/16 md5
          - hostssl all all all md5

  instances:
    - name: postgres
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-sqq
      replicas: &replica 3
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/data: postgres

  users:
    - name: "postgres"
      databases:
        - "postgres"
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    - name: "sqqvgprod"
      databases:
        - "sqqvgprod"
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
  backups:
    pgbackrest:
      global:
        compress-type: "bz2"
        compress-level: "9"
        repo1-block: "y"
        repo1-bundle: "y"
        repo1-path: /crunchy-pgo-sqq
        repo1-retention-full: "30" # days
        repo1-retention-full-type: "time"
      manual:
        repoName: repo1
        options:
          - --type=full
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-sqq-backup
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              storageClassName: ""
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
              selector:
                matchLabels:
                  app.kubernetes.io/component: sqq-pgbackrest-repo
          schedules:
            full: "0 1 * * 0" # Sunday at 01:00
            differential: "0 1 * * 1-6" # Mon-Sat at 01:00
            incremental: "0 2-23 * * *" # Every hour except 01:00

  monitoring:
    pgmonitor:
      exporter:
        resources:
          requests:
            cpu: 10m
            memory: 64M
          limits:
            memory: 512M

  proxy:
    pgBouncer:
      port: 5432
      replicas: *replica
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-sqq-pgbouncer
      config:
        global:
          pool_mode: "transaction"
          client_tls_sslmode: prefer
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/role: "pgbouncer"
