apiVersion: v1
kind: Secret
metadata:
    name: volsync-maintenance-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:dRuD8biH29uqQBymRM8Y2ChpE2ZeroBSkkd3MB4jsaycfldalOKCxqIyHaOk3TlFh5PvdMpZE2SmtAIXhDrGHA==,iv:7gQ/ZhQY1SopYzsTdMnTtMrmK4wd1Ynp35XutI9tliE=,tag:Ew9ZS69Y6/imERVmI7XO7g==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:L6GIFUo4ImLA2XTo30qX11jr57sZrkwyqVbVww==,iv:9pJqYfb4d09oLzkwcemDMBI5YRiaSDK4lh4h7pmkHaw=,tag:3v6nBdMCJClMn+QsS9HpkQ==,type:str]
sops:
    age:
        - recipient: age18vvdvrkqql3pk74p72gawhlrk5ukltsz826cjt363kpdc8nnhs2suxews3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSGZ0dnVrQ1ZYWWdRRjY0
            OWtFMEJyTmpvOE1QR29UdXFsZnVTZXFQTEhRCldjWGR6UEFMNjdhZ252dVRONGMr
            V2NsZG8wR0FkM3l3Uk42SU9HemsxeGcKLS0tIDQveXpLVU9oZHM2RllpUjRXN0Fj
            dlE2SDJBVEVaQllDSmRoOElEMFNWSEUKu4uYpVAhhcH2d+4qtEruA2xSRWS2FTNe
            hpk99irpvCtA3RCQ7UhRH7zpOkE3aBrFq/h5RnfyLRue3bUXQPOycQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T21:00:28Z"
    mac: ENC[AES256_GCM,data:OCexXv3vldO4LhPQhFTQL/WWzkqjI66AZRn1yBfl7U6mdsnizdQOMmqiAPH86Hjqsvqncw+VNKF2dZqeW6sLm23VMSAZ6NqvBSoFRZCX5xb2iip4gIkicu1X5jm5JE3aW2il3zvP6SAG1NVeDxsvDO7qVxwhiJDgi5IS72lGFCI=,iv:LdthkF7iaWAyHBSY4seJ+N2iFyrz1ufQvuItYrB+aZg=,tag:VOQCBM34WV89KAXhwFLoVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
