apiVersion: v1
kind: Secret
metadata:
    name: vault-unseal-keys
    namespace: vault
type: Opaque
stringData:
    #ENC[AES256_GCM,data:I25Gzr2sAwBtc19VunZS9HbBRJSgnkO0S3z0MVtLXGskHTymdbyf/0oB1YZaqaB3aADdoY93ljE=,iv:1ebDQfQ6xSmmjgjO9ygWBhH8OVLinnW8UPrm+Y7h5qw=,tag:lFdTRJmHYDphbclmzjtRhQ==,type:comment]
    #ENC[AES256_GCM,data:2P9eGlmCEKXhLL13XpFvl1AGnSjDk5SFIUqMKgUOrqjhZ9e0U600miQPBlyOVkR8jo9v5G48NQMpqOtj08g+mw==,iv:oCVMqowLaQdKdG/w9b6bjEHZH4/mX2a73vq+ofFSQQ4=,tag:bSQ42Mw8KNouVQjcJMUSMg==,type:comment]
    VAULT_UNSEAL_KEYS: ENC[AES256_GCM,data:SzVi1GTnYGl3XuF78R2Eao5uKWzybiqVm3BakEDxuZQjYAudv/oQWdNKq8BL95F1MCeofIpsFMvTlePFpujqgWQ=,iv:vQgwxfETJ+/slPz5Pds1XLsOSR3SZmwDB5b/y7DrFB8=,tag:fELx+4DR4wxbPbZqp4eVmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdExYaEkrampEdDAwRXVq
            d211Z0JTYVU1ZnloOFI5N1BFV2NvdHFaS2tzCnU2SFdIZEswaHlIdk1DUGZORm83
            ekdqVGtGc0FIeDNuYWVmTDEyZE1sL1EKLS0tIFJaMzV3UjcxZzhpcHBSZ1IrdTJF
            TXdiRjYzbEhBVmtRTUtBR0k1Z2ZDeDgK23XuFJ8ZvOFCAdPSEYbquVHFYtCZCIHY
            XMpzTwZfTMn2n11O39ig+nkYX9vPyvAD/S968dwehVAeyRAMXcUhBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18vvdvrkqql3pk74p72gawhlrk5ukltsz826cjt363kpdc8nnhs2suxews3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T14:47:55Z"
    mac: ENC[AES256_GCM,data:NmVHC8LVdfG31E/1KSINdmoqR7DJGLp793ZM/+gKkvDa7GfRplTPH3nRZwoslcifGJPmsdBA8jq2nv0jErmpB1TDylBVYTvbq3jQ/374sPAU7V+ZsJ6xz+KJMQlJPmkukdCEekveeo+rvvJpDUOYNbnKtMGu191YcORM4CvzzkM=,iv:+uafHeQh4ImBpVIojIeQP4Zc78N6iuqOyIpsAPAa6Y8=,tag:yw0Vo3gJ643XIs5WHPWcLg==,type:str]
    version: 3.13.1
