---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-16-pgbackrest-repo
  labels:
    app.kubernetes.io/component: postgres-16-pgbackrest-repo
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: "truenas.${INTERNAL_DOMAIN}"
    path: /mnt/tank/Backup/postgresql/postgres-16
