---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: accueil-staging
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: accueil-staging-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ENV: "{{ .ENV }}"
        TZ: "Europe/Paris"
        ERP_URL: "{{ .ERP_URL }}"
        ERP_LOGIN: "{{ .ERP_LOGIN }}"
        ERP_PASSWORD: "{{ .ERP_PASSWORD }}"
        ERP_DB: "{{ .ERP_DB }}"
        EMAIL_BDM: "{{ .EMAIL_BDM }}"
        EMAIL_LOGIN: "{{ .EMAIL_LOGIN }}"
        EMAIL_PASSWORD: "{{ .EMAIL_PASSWORD }}"
        SMTP_SERVER: "{{ .SMTP_SERVER }}"
  dataFrom:
    - extract:
        key: apps/sqq/accueil-staging
