---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app changedetection
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      app:
        containers:
          main:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: "0.54.7@sha256:b632a9fb6be702fb859e02cd5cac5de7a7466ce1e97f5f5347a1d012c0720108"

            env:
              TZ: ${CONFIG_TIMEZONE}
              PORT: &port 5000
              USE_X_SETTINGS: 1
              PLAYWRIGHT_DRIVER_URL: ws://localhost:9222

          browser:
            image:
              repository: docker.io/lightpanda/browser
              tag: nightly
              pullPolicy: IfNotPresent

            args:
              - lightpanda
              - serve
              - --host
              - 0.0.0.0
              - --port
              - "9222"

    service:
      app:
        controller: app
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${LIMITED_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network

        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      datastore:
        existingClaim: *app
