---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app changedetection
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      app:
        containers:
          main:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: "0.54.6@sha256:7611738e564caa08a9b7591a7909e4f6c78d34d289873b9fd7d320af50943419"

            env:
              TZ: ${CONFIG_TIMEZONE}
              PORT: &port 5000
              USE_X_SETTINGS: 1
              PLAYWRIGHT_DRIVER_URL: ws://localhost:9222/?stealth=1&--disable-web-security=true&--user-data-dir=~/browserless-cache-123

          browser:
            image:
              repository: docker.io/lightpanda/browser
              tag: nightly
              pullPolicy: IfNotPresent

            args:
              - serve
              - --host
              - 0.0.0.0
              - --port
              - "9222"

    service:
      app:
        controller: app
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${LIMITED_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network

        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      datastore:
        existingClaim: *app
