---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: forgejo-runner-secret
    template:
      engineVersion: v2
      data:
        token: "{{ .FORGEJO_RUNNER_TOKEN }}"
        uuid: "{{ .FORGEJO_RUNNER_UUID }}"
  dataFrom:
    - extract:
        key: development/forgejo
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
