### Purge matrix room
DELETE {{matrix_url}}/_synapse/admin/v1/rooms/{{matrix_room}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{matrix_token}}

{
  "purge": true,
  "message": "Sorry - kicking you out to clean up the database"
}

### List media size per user
GET {{matrix_url}}/_synapse/admin/v1/statistics/users/media
Accept: application/json
Authorization: Bearer {{matrix_token}}

### Create MXC
POST {{matrix_url}}/_matrix/media/v1/create
Accept: application/json
Authorization: Bearer {{matrix_token}}

### Upload an image to the Matrix Content Repository
PUT  https://{{matrix_url}}/_matrix/media/v3/upload/hoohoot.org/OLmAYFgLbMGzEAXjpIRqHPGY?filename=jellystat.png
Authorization: Bearer {{matrix_token}}
Content-Type: application/octet-stream

< /home/lucas/Downloads/jellystat.png

### Send a message with a linked image
PUT https://{{matrix_url}}/_matrix/client/r0/rooms/{{matrix_room}}/send/m.room.message/{{$random.uuid}}
Content-Type: application/json
Authorization: Bearer {{matrix_token}}

{
  "msgtype": "m.text",
  "body": "This is a text description and an image.",
  "format": "org.matrix.custom.html",
  "formatted_body": "<h1>Movie Downloaded</h1><p>The Wild Robot (2024) [WEBDL-1080p] https://www.imdb.com/title/tt29623480/<br>Requested by : Michel<br>Description: Earum quos libero placeat consequuntur. Necessitatibus assumenda molestiae et iure ipsum officia quia quo. Aut consectetur doloribus accusantium perferendis optio autem esse. Ratione omnis assumenda reiciendis a. Molestias laudantium sit odit excepturi aspernatur dolorum aliquid consectetur. Et aut sunt excepturi nam pariatur.…</p>"
}

### Make user room admin
POST https://{{matrix_url}}/_synapse/admin/v1/rooms/{{matrix_room}}/make_room_admin
Content-Type: application/json
Authorization: Bearer {{matrix_token}}

{
    "user_id": "{{matrix_admin}}"
}

### Delete local media by date
POST https://{{matrix_url}}/_synapse/admin/v1/media/delete?before_ts=1725184800000
Content-Type: application/json
Authorization: Bearer {{matrix_token}}

{}
