---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: crunchy-pgo-sqq-secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: sqq
      server:
        caProvider:
          type: "ConfigMap"
          name: "kube-root-ca.crt"
          namespace: sqq
          key: "ca.crt"
      auth:
        serviceAccount:
          name: external-secrets-pg-sqq
          namespace: sqq
