---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: semaphore
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: semaphore-secret
    template:
      engineVersion: v2
      data:
        # PostgreSQL
        SEMAPHORE_DB_DIALECT: postgres
        SEMAPHORE_DB_HOST: "{{ .pg_host }}"
        SEMAPHORE_DB_PORT: "{{ .pg_port }}"
        SEMAPHORE_DB_USER: "{{ .pg_user }}"
        SEMAPHORE_DB_PASS: "{{ .pg_password }}"
        SEMAPHORE_DB: "{{ .pg_dbname }}"
        # Admin bootstrap (created on first run only)
        SEMAPHORE_ADMIN: admin
        SEMAPHORE_ADMIN_NAME: Administrator
        SEMAPHORE_ADMIN_EMAIL: "semaphore@${SECRET_DOMAIN}"
        SEMAPHORE_ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        # 32-byte base64 key used to encrypt stored access keys / secrets
        SEMAPHORE_ACCESS_KEY_ENCRYPTION: "{{ .ACCESS_KEY_ENCRYPTION }}"
  dataFrom:
    - extract:
        key: development/semaphore
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-semaphore
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
