---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app agentgateway
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    monitoring:
      enabled: true
      grafanaDashboard:
        enabled: false
    controller:
      image:
        pullPolicy: IfNotPresent
