{
 "title": "Dashboard for smartctl_exporter",
 "description": "prometheus-community\r\n/\r\nsmartctl_exporter\r\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(smartctl_version,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SMART General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature NVMe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{instance=~\"$instance\",device=~\"nvme.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Temperature sdX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{instance=~\"$instance\",device=~\"sd.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power on Time NVMe",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_on_seconds{instance=~\"$instance\",device=~\"nvme0n1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power on Time sdX",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_on_seconds{instance=~\"$instance\",device=~\"sda\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Cycle NVMe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_cycle_count{instance=~\"$instance\",device=\"nvme0n1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Cycle sdX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_cycle_count{instance=~\"$instance\",device=\"sda\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Smart Status NVMe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_smart_status{instance=~\"$instance\",device=\"nvme0n1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Smart Status sdX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_smart_status{instance=~\"$instance\",device=~\"sd.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data Written NVMe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "smartctl_device_bytes_written{instance=~\"$instance\",device=\"nvme0n1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Spare on NVME",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_available_spare{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Device Media Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_media_errors{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Log Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_error_log_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Device Critical Warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_critical_warning{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}