---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustical-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: rustical-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-id: "{{ .RUSTICAL_OIDC__CLIENT_ID }}"
        client-secret: "{{ .RUSTICAL_OIDC__CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: default/rustical
