---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.21.0@sha256:4e1e8d98b883009cb849851857e277109c21db1c2d857ae61e14de894f2169ff
            env:
              BASE_URL: https://recettes.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: mealie-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
                memory: 400Mi
              limits:
                memory: 600Mi
    service:
      app:
        ports:
          http:
            port: 9000
    route:
      app:
        hostnames:
          - recettes.${SECRET_DOMAIN}
        parentRefs:
          - name: external
            namespace: network
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/data
