---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sprout-track
spec:
  refreshInterval: 1m
  target:
    name: sprout-track-secret
    template:
      type: Opaque
      data:
        DATABASE_URL: >-
          postgresql://{{ index . "user" }}:{{ index . "password" }}@{{ index . "host" }}:{{ index . "port" }}/sprouttrack
        LOG_DATABASE_URL: >-
          postgresql://{{ index . "user" }}:{{ index . "password" }}@{{ index . "host" }}:{{ index . "port" }}/sprouttrack_logs
        ENC_HASH: "{{ .ENC_HASH }}"
        NOTIFICATION_CRON_SECRET: "{{ .NOTIFICATION_CRON_SECRET }}"
  dataFrom:
    - extract:
        key: postgres-16-pguser-sprouttrack
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore
    - extract:
        key: home/sprout-track
      sourceRef:
        storeRef:
          name: hashicorp-vault
          kind: ClusterSecretStore
