---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tracearr-timescaledb
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/apps/media/tracearr/timescaledb
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 1h
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 20Gi
      VOLSYNC_PUID: "1000"
      VOLSYNC_PGID: "1000"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tracearr
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/dragonfly
    - ../../../../components/volsync
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: dragonfly
      namespace: flux-system
    - name: tracearr-timescaledb
      namespace: flux-system
  path: ./kubernetes/apps/media/tracearr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 1h
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
      DRAGONFLY_ARG_CLUSTER_MODE: "--cluster_mode="
      DRAGONFLY_ARG_LOCK_ON_HASHTAGS: "--lock_on_hashtags=false"
      DRAGONFLY_ARGS_DEFAULT_LUA_FLAGS: allow-undeclared-keys
      DRAGONFLY_LIMITS_MEMORY: 4Gi
