---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: firefly-secret
    template:
      engineVersion: v2
      data:
        APP_KEY: "{{ .APP_KEY }}"
        APP_CIPHER: AES-128-CBC
        DB_CONNECTION: "pgsql"
        DB_HOST: "{{ .pg_host }}"
        DB_PORT: "{{ .pg_port }}"
        DB_DATABASE: "{{ .pg_dbname }}"
        DB_USERNAME: "{{ .pg_user }}"
        DB_PASSWORD: "{{ .pg_password }}"
  dataFrom:
    - extract:
        key: default/firefly
    - extract:
        key: postgres-16-pguser-firefly
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
