---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app firefly
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      firefly:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: docker.io/fireflyiii/core
              tag: version-6.2.27

            env:
              APP_ENV: production
              APP_DEBUG: "false"
              APP_URL: "https://firefly.${SECRET_DOMAIN}"
              TZ: "${TIMEZONE}"
              TRUSTED_PROXIES: "**"
              LOG_CHANNEL: stack
              APP_LOG_LEVEL: notice
              DEFAULT_LANGUAGE: fr_FR
              DEFAULT_LOCALE: equal
              SITE_OWNER: "firefly@${SECRET_DOMAIN}"
              MAIL_MAILER: smtp
              MAIL_HOST: smtp-relay.infrastructure.svc.cluster.local
              MAIL_PORT: "2525"
              MAIL_FROM: "firefly@${SECRET_DOMAIN}"

            envFrom:
              - secretRef:
                  name: firefly-secret

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /login
                    port: &port 8080
                  initialDelaySeconds: 60
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes

            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            group: Misc
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: external
            namespace: network

        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      upload:
        existingClaim: *app
        globalMounts:
          - path: /var/www/html/storage/upload
