---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sesame
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: sesame-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ODOO_URL: "{{ .ODOO_URL }}"
        ODOO_DATABASE: "{{ .ODOO_DATABASE }}"
        ODOO_LOGIN: "{{ .ODOO_LOGIN }}"
        ODOO_PASSWORD: "{{ .ODOO_PASSWORD }}"
  dataFrom:
    - extract:
        key: sqq/sesame
