---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sesame
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      main:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/superquinquin-sur-deule/sesame
              tag: latest@sha256:ea8c4d371b649471d360209bc821e43fc6731b7c9a88aa1fa0eb1853d708cf5f

            envFrom:
              - secretRef:
                  name: sesame-secret

            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi

    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8080

    route:
      app:
        hostnames:
          - "sesame.${SQQ_DOMAIN}"
        parentRefs:
          - name: external
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
