---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sesame
spec:
  endpoints:
    - interval: 1m
      path: /q/metrics
      port: http
      scheme: http
      scrapeTimeout: 10s
  jobLabel: sesame
  namespaceSelector:
    matchNames:
      - sqq
  selector:
    matchLabels:
      app.kubernetes.io/instance: sesame
      app.kubernetes.io/name: sesame
      app.kubernetes.io/service: sesame
