apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard-password
data:
    password: ENC[AES256_GCM,data:GB/tvKTSNw3evNlM78YXWrBy232ViIyW7e0anMZ68iM=,iv:56jLP5pLLMurEnxtpjSFgqJaehLxEzzsoVQ1ZBDP0/8=,tag:ULDEDuz7f/rFaF8+PSRlLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18vvdvrkqql3pk74p72gawhlrk5ukltsz826cjt363kpdc8nnhs2suxews3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROXBuRldDTVhvVmxRd3Fp
            bTB5NzFSWDRHL1kyNTlQcUkwaEJrUVVSSkNFCkxSRmpQTEJhNkhvUlhPRWc3bHox
            TktQMWR5TjNOQ21TMWNhdTdOWklQK2MKLS0tIGh5Z3JES1FtY3BFZndod0F2Q0hJ
            bHptRHl3MVV5NE8yWW5CaGxVMWFjWlUKIOywLsbg/rHHq0TrpC2pY7jHvJakTzc3
            RKGyHdBT3/TsXezHZoN7TAxKoSbWO9cqznbyYLpdHKfRXGFymM2MdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T11:27:57Z"
    mac: ENC[AES256_GCM,data:8h2n/Y+ZG8glZJv5j7ptXSiVt20H/iRd/te99UVH4uHq3TyMYCyETk7iu/26BjKK0JvVODiV2lvcwe5c/u5BU9+rKa6WyAz6828IEceq47CiBTG7wAqcZknEEKeOBCM8qYfJJz+v3Y1wLYP5gd9T4proqiHOR+vEajvCSqK8vtY=,iv:8dV1JMoYTOv7YxgpPo8YRTouh1WmNB6g3rChg089Xo8=,tag:C4efOiVqI85jWCMLfkiMyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
