---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: sparkyfitness-secret
    template:
      engineVersion: v2
      data:
        SPARKY_FITNESS_DB_HOST: '{{ .pg_host }}'
        SPARKY_FITNESS_DB_PORT: '{{ .pg_port }}'
        SPARKY_FITNESS_DB_NAME: '{{ .pg_dbname }}'
        SPARKY_FITNESS_DB_USER: '{{ .pg_user }}'
        SPARKY_FITNESS_DB_PASSWORD: '{{ .pg_password }}'
        SPARKY_FITNESS_APP_DB_USER: '{{ .pg_user }}'
        SPARKY_FITNESS_APP_DB_PASSWORD: '{{ .pg_password }}'
        SPARKY_FITNESS_API_ENCRYPTION_KEY: '{{ .SPARKY_FITNESS_API_ENCRYPTION_KEY }}'
        BETTER_AUTH_SECRET: '{{ .BETTER_AUTH_SECRET }}'
        SPARKY_FITNESS_OIDC_CLIENT_SECRET: '{{ .SPARKY_FITNESS_OIDC_CLIENT_SECRET }}'
        DB_URI: 'postgresql://{{ .pg_user }}:{{ .pg_password }}@{{ .pg_host }}:{{ .pg_port }}/{{ .pg_dbname }}'
  dataFrom:
    - extract:
        key: default/sparkyfitness
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-sparkyfitness
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
