---
apiVersion: authentik.starry.blue/v1alpha1
kind: AuthentikApplication
metadata:
  name: bookorbit
spec:
  slug: bookorbit
  name: Bookorbit
  adopt: IfMatch
  provider:
    flows:
      authorization:
        slug: default-provider-authorization-implicit-consent
      invalidation:
        slug: default-provider-invalidation-flow
    oauth2:
      clientType: Confidential
      redirectURIs:
        - url: "https://bookorbit.hoohoot.org/oauth2-callback"
          matchingMode: Strict
          type: Authorization
      scopes:
        - scopeName: openid
        - scopeName: email
        - scopeName: profile
      grantTypes:
        - AuthorizationCode
        - Implicit
        - Hybrid
        - RefreshToken
        - ClientCredentials
        - Password
        - DeviceCode
      subjectMode: UserID
      issuerMode: PerProvider
      includeClaimsInIDToken: true
  access:
    rules:
      - group:
          name: Hoohoot Users
