---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookorbit
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: bookorbit-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "{{ .pg_uri }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        SETUP_BOOTSTRAP_TOKEN: "{{ .SETUP_BOOTSTRAP_TOKEN }}"
        EMAIL_ENCRYPTION_KEY: "{{ .EMAIL_ENCRYPTION_KEY }}"
        MIGRATION_ENCRYPTION_KEY: "{{ .MIGRATION_ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: media/bookorbit
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
    - extract:
        key: postgres-16-pguser-bookorbit
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
