---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sqq-keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-sqq-secrets
  target:
    name: sqq-keycloak-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        KC_DB_URL: '{{ index . "pg_jdbc-uri" }}'
        KC_BOOTSTRAP_ADMIN_USERNAME: "{{ .KC_BOOTSTRAP_ADMIN_USERNAME }}"
        KC_BOOTSTRAP_ADMIN_PASSWORD: "{{ .KC_BOOTSTRAP_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: postgres-sqq-pguser-keycloak
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-sqq-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
    - extract:
        key: sqq/keycloak
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: hashicorp-vault
