---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app firefly-importer
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      firefly-importer:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: docker.io/fireflyiii/data-importer
              tag: version-2.3.2

            env:
              APP_ENV: production
              APP_DEBUG: "false"
              APP_URL: "https://firefly-importer.${LIMITED_DOMAIN}"
              TZ: "${TIMEZONE}"
              TRUSTED_PROXIES: "**"
              LOG_CHANNEL: stack
              FIREFLY_III_URL: "http://firefly.default.svc.cluster.local:8080"
              VANITY_URL: "https://firefly.${SECRET_DOMAIN}"
              CAN_POST_FILES: "true"
              CAN_POST_AUTOIMPORT: "true"

            envFrom:
              - secretRef:
                  name: firefly-importer-secret

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes

            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    persistence:
      import:
        existingClaim: firefly-importer-import
        globalMounts:
          - path: /import

    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            group: Misc
        hostnames:
          - "{{ .Release.Name }}.${LIMITED_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network

        rules:
          - backendRefs:
              - name: *app
                port: *port
